### ISSUE TITLE
add gitmemory link?

### ISSUE THREAD

**Issue by hartzis** [hartzis/hartzis.me#4]
- https://www.gitmemory.com/hartzis
  - provides a really interesting and detailed overview of open source work

**Comment by towry** [comment]
Better not.

Gitmemory is a junk site that collect data from Github and provide nothing but same static content of github, it appears on google search results, waste other people's time.

See:

- https://news.ycombinator.com/item?id=27456600
- https://www.reddit.com/r/github/comments/iiolp8/what_the_hell_is_gitmemorycom/

**Comment by hartzis** [comment]
@towry thanks for the info!
